<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" PrivateAssets="all" Version="3.8.4" />
    <!-- <PackageReference Include="nkast.Kni.Platform.SDL2.GL"   PrivateAssets="all" Version="4.1.9001"/> -->
  </ItemGroup>
  <!--
  <PropertyGroup>
    <MonoGameNetStandardVersion>3.8.1.2082-develop</MonoGameNetStandardVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" PrivateAssets="all" Version="3.8.1.303" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Update="MonoGame.Framework.DesktopGL" Version="$(MonoGameNetStandardVersion)" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Update="MonoGame.Framework.DesktopGL" Version="$(MonoGameNetStandardVersion)" />
  </ItemGroup>  
  -->
</Project>